toletwebapp/Models/Building.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace toletwebapp.Models
{
    public class Building
    {
        [Key]

        public Guid Id { get; set; }= Guid.NewGuid();
        public string Block { get; set; }
        public string Road { get; set; }
        public string House { get; set; }
        public DateTime ClosingTime { get; set; }
        public string Image { get; set; } = "noimage.png";
        public string Description { get; set; } = "Notes";
        public string Note { get; set; } = "Note about building";
        public bool GarageAvailable { get; set; } = true;
        public bool LiftAvailable { get; set; } = true;
        public string Security { get; set; } = "Highly secured 24/7 ";

        [NotMapped]
        public IFormFile ImageUpload { get; set; }

    }
}

toletwebapp/Controllers/BuildingController.cs
using Microsoft.AspNetCore.Mvc;
using toletwebapp.Contexts;
using toletwebapp.Models;

namespace toletwebapp.Controllers
{
    public class BuildingController : Controller
    {
        private readonly IdentityDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public BuildingController(IdentityDbContext db, IWebHostEnvironment wb)
        {
            _db = db;
            _webHostEnvironment = wb;
        }
        public IActionResult Index()
        {
            return View(_db.Buildings.ToList());
        }


        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Building product)
        {
            //ViewBag.Categories = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);
            
            if (ModelState.IsValid)
            {
                

                if (product.ImageUpload != null)
                {
                    string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media/products");
                    string imageName = Guid.NewGuid().ToString() + "_" + product.ImageUpload.FileName;

                    string filePath = Path.Combine(uploadsDir, imageName);

                    FileStream fs = new FileStream(filePath, FileMode.Create);
                    await product.ImageUpload.CopyToAsync(fs);
                    fs.Close();

                    product.Image = imageName;
                }

                _db.Buildings.Add(product);
                await _db.SaveChangesAsync();
                TempData["Success"] = "The product has been created!";
                return RedirectToAction("Index");
            }

            return View(product);
        }



        //EDIT

        public async Task<IActionResult> Edit(Guid id)
        {
            Building product = await _db.Buildings.FindAsync(id);
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Building product)
        {
            //ViewBag.Categories = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);

            if (product.ImageUpload != null)
            {
                string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media/products");
                string imageName = Guid.NewGuid().ToString() + "_" + product.ImageUpload.FileName;

                string filePath = Path.Combine(uploadsDir, imageName);

                FileStream fs = new FileStream(filePath, FileMode.Create);
                await product.ImageUpload.CopyToAsync(fs);
                fs.Close();

                product.Image = imageName;
            }

            _db.Update(product);
            await _db.SaveChangesAsync();

            TempData["Success"] = "The product has been edited!";

            return Redirect("/Building/Index");
        }



        public async Task<IActionResult> CreateFlat(Guid id)
        {
            Building product = await _db.Buildings.FindAsync(id);
            Flat flat = new Flat();
            flat.Building = product;
            return View(flat);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateFlat(Guid id, Flat product)
        {
            //ViewBag.Categories = new SelectList(_context.Categories, "Id", "Name", product.CategoryId);

            if (product.ImageUpload1 != null)
            {
                string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media/products");
                string imageName = Guid.NewGuid().ToString() + "_" + product.ImageUpload1.FileName;

                string filePath = Path.Combine(uploadsDir, imageName);

                FileStream fs = new FileStream(filePath, FileMode.Create);
                await product.ImageUpload1.CopyToAsync(fs);
                fs.Close();

                product.Image1 = imageName;
            }
            if (product.ImageUpload2 != null)
            {
                string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media/products");
                string imageName = Guid.NewGuid().ToString() + "_" + product.ImageUpload2.FileName;

                string filePath = Path.Combine(uploadsDir, imageName);

                FileStream fs = new FileStream(filePath, FileMode.Create);
                await product.ImageUpload2.CopyToAsync(fs);
                fs.Close();

                product.Image2 = imageName;
            }
            if (product.ImageUpload3 != null)
            {
                string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media/products");
                string imageName = Guid.NewGuid().ToString() + "_" + product.ImageUpload3.FileName;

                string filePath = Path.Combine(uploadsDir, imageName);

                FileStream fs = new FileStream(filePath, FileMode.Create);
                await product.ImageUpload3.CopyToAsync(fs);
                fs.Close();

                product.Image3 = imageName;
            }

            if (product.ImageUpload4 != null)
            {
                string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media/products");
                string imageName = Guid.NewGuid().ToString() + "_" + product.ImageUpload4.FileName;

                string filePath = Path.Combine(uploadsDir, imageName);

                FileStream fs = new FileStream(filePath, FileMode.Create);
                await product.ImageUpload4.CopyToAsync(fs);
                fs.Close();

                product.Image4 = imageName;
            }

            if (product.ImageUpload5 != null)
            {
                string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media/products");
                string imageName = Guid.NewGuid().ToString() + "_" + product.ImageUpload5.FileName;

                string filePath = Path.Combine(uploadsDir, imageName);

                FileStream fs = new FileStream(filePath, FileMode.Create);
                await product.ImageUpload5.CopyToAsync(fs);
                fs.Close();

                product.Image5 = imageName;
            }

            _db.Flats.Add(product);
            await _db.SaveChangesAsync();

            TempData["Success"] = "The Flat has been updated!";

            return Redirect("/Building/Index");
        }








        //FLAT

    }
}

toletwebapp/Controllers/FlatController.cs
using Microsoft.AspNetCore.Mvc;
using toletwebapp.Contexts;
using toletwebapp.Models;

namespace toletwebapp.Controllers
{
    public class FlatController : Controller
    {
        private readonly IdentityDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public FlatController(IdentityDbContext db, IWebHostEnvironment wb)
        {
            _db = db;
            _webHostEnvironment = wb;
        }
        public IActionResult Index(Guid id)
        {
            return View(_db.Flats.Where(u=>u.Id==id).ToList());
        }
        public IActionResult Details(int id) {
            var flat = _db.Flats.Find(id);
            var building = _db.Buildings.Find(flat.Id);
            flat.Building = building;
            return View(flat);
        }
    }
}

toletwebapp/Views/Building/Create.cshtml
@model toletwebapp.Models.Building

@{
        ViewData["Title"] = "Create";
}

<h1>Create Building</h1>

<div class="row">
        <div class="col-md-4">
                <form asp-action="Create" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                                <label asp-for="Block" class="control-label"></label>
                                <input asp-for="Block" class="form-control" />
                                <span asp-validation-for="Road" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                                <label asp-for="Road" class="control-label"></label>
                                <input asp-for="Road" class="form-control" />
                                <span asp-validation-for="Road " class="text-danger"></span>
                        </div>
                       <div class="form-group">
                                <label asp-for="House" class="control-label"></label>
                                <input asp-for="House" class="form-control" />
                                <span asp-validation-for="House" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                                <label asp-for="Note" class="control-label"></label>
                                <input asp-for="Note" class="form-control" />
                                <span asp-validation-for="Note " class="text-danger"></span>
                        </div>

                        <div class="row">
                            <div class="col">
                            <label>
                                <input asp-for="GarageAvailable" type="checkbox">
                                Garage Available: 
                            </label>
                            </div>
                            <div class="col">
                                                        
                            <label>
                                <input asp-for="LiftAvailable" type="checkbox">
                                Lift Available:
                            </label>
                            </div>

                        </div>


                        <div class="form-group">
                                <label asp-for="Image" class="control-label"></label>
                                <input asp-for="ImageUpload" class="form-control" />
                                <img id="imgpreview" class="pt-2" />
                                <span asp-validation-for="ImageUpload" class="text-danger"></span>
                        </div>


                        <div class="form-group">
                                <button class="btn btn-primary" type="submit">Create</button>
                        </div>
                </form>
        </div>
</div>

<div>
        <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

<script src="https://cdn.ckeditor.com/4.19.0/standard/ckeditor.js"></script>
<script>
        $("#ImageUpload").change(function() {
                readURL(this);
        });
        CKEDITOR.replace( 'Description' );
</script>

}

toletwebapp/Views/Building/CreateFlat.cshtml
@model toletwebapp.Models.Flat

@{
        ViewData["Title"] = "Edit";
}

<h1>Create Flat</h1>

<div class="row">
        <div class="col-md-4">
                <form asp-action="CreateFlat" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                <label asp-for="Image1" class="control-label"></label>
                                <input asp-for="ImageUpload1" class="form-control" />
                                <img id="imgpreview" class="pt-2" />
                                <span asp-validation-for="ImageUpload1" class="text-danger"></span>
                        </div>
                        
                         <div class="form-group">
                                <label asp-for="Image2" class="control-label"></label>
                                <input asp-for="ImageUpload2" class="form-control" />
                                <img id="imgpreview" class="pt-2" />
                                <span asp-validation-for="ImageUpload2" class="text-danger"></span>
                        </div>
                        
                         <div class="form-group">
                                <label asp-for="Image3" class="control-label"></label>
                                <input asp-for="ImageUpload3" class="form-control" />
                                <img id="imgpreview" class="pt-2" />
                                <span asp-validation-for="ImageUpload3" class="text-danger"></span>
                        </div>
                        
                         <div class="form-group">
                                <label asp-for="Image4" class="control-label"></label>
                                <input asp-for="ImageUpload4" class="form-control" />
                                <img id="imgpreview" class="pt-2" />
                                <span asp-validation-for="ImageUpload4" class="text-danger"></span>
                        </div>
                        
                         <div class="form-group">
                                <label asp-for="Image5" class="control-label"></label>
                                <input asp-for="ImageUpload5" class="form-control" />
                                <img id="imgpreview" class="pt-2" />
                                <span asp-validation-for="ImageUpload5" class="text-danger"></span>
                        </div>
                            </div>
                            <div class="col">
                                 <div class="form-group">
                                <label asp-for="Size" class="control-label"></label>
                                <input asp-for="Size" class="form-control" />
                                <span asp-validation-for="Size" class="text-danger"></span>
                        </div>

                        
                        <div class="form-group">
                                <label asp-for="Beds" class="control-label"></label>
                                <input asp-for="Beds" class="form-control" />
                                <span asp-validation-for="Beds" class="text-danger"></span>
                        </div>
                                                <div class="form-group">
                                <label asp-for="Baths" class="control-label"></label>
                                <input asp-for="Baths" class="form-control" />
                                <span asp-validation-for="Baths" class="text-danger"></span>
                        </div>
                         <div class="form-group">
                                <label asp-for="Balcony" class="control-label"></label>
                                <input asp-for="Balcony" class="form-control" />
                                <span asp-validation-for="Balcony" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                                <label asp-for="PhoneNumber" class="control-label"></label>
                                <input asp-for="PhoneNumber" class="form-control" />
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                                                <div class="form-group">
                                <label asp-for="Rent" class="control-label"></label>
                                <input asp-for="Rent" class="form-control" />
                                <span asp-validation-for="Rent" class="text-danger"></span>
                        </div>
                            </div>
                        </div>
                         




                       

                        <div class="form-group">
                                <button class="btn btn-primary">Create Flat</button>
                        </div>
                </form>
        </div>
</div>

<div>
        <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

<script src="https://cdn.ckeditor.com/4.19.0/standard/ckeditor.js"></script>
<script>
        $("#ImageUpload").change(function() {
                readURL(this);
        });
        CKEDITOR.replace( 'Description' );
</script>

}

toletwebapp/Views/Building/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

toletwebapp/Views/Building/Edit.cshtml
@model toletwebapp.Models.Building

@{
        ViewData["Title"] = "Edit";
}

<h1>Edit Building</h1>

<div class="row">
        <div class="col-md-4">
                <form asp-action="Edit" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <input type="hidden" asp-for="Image" />

                        <div class="form-group">
                                <label asp-for="Block" class="control-label"></label>
                                <input asp-for="Block" class="form-control" />
                                <span asp-validation-for="Block" class="text-danger"></span>
                        </div>

                        
                        <div class="form-group">
                                <label asp-for="Road" class="control-label"></label>
                                <input asp-for="Road" class="form-control" />
                                <span asp-validation-for="Road" class="text-danger"></span>
                        </div>
                         <div class="form-group">
                                <label asp-for="House" class="control-label"></label>
                                <input asp-for="House" class="form-control" />
                                <span asp-validation-for="House" class="text-danger"></span>
                        </div>
                                                <div class="form-group">
                                <label asp-for="Note" class="control-label"></label>
                                <input asp-for="Note" class="form-control" />
                                <span asp-validation-for="Note" class="text-danger"></span>
                        </div>


                        <div class="form-group">
                                <button class="btn btn-primary">Edit</button>
                        </div>
                </form>
        </div>

        <div class="col-md-4">
            <a asp-controller="Building" asp-action="CreateFlat" asp-route-id="@Model.Id" class="btn btn-primary">
               Create Flat here 
            </a>
            <a asp-controller="Flat" asp-action="Index" asp-route-id="@Model.Id" class="btn btn-primary">
                View Flats
            </a>


        </div>
</div>

<div>
        <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

<script src="https://cdn.ckeditor.com/4.19.0/standard/ckeditor.js"></script>
<script>
        $("#ImageUpload").change(function() {
                readURL(this);
        });
        CKEDITOR.replace( 'Description' );
</script>

}

toletwebapp/Views/Building/Index.cshtml
@model IEnumerable<Building>

@{
        ViewData["Title"] = "Products";
}

<h1>Buildings</h1>

<p>
        <a asp-action="Create">Create New</a>
</p>


<div class="row" style="padding-left:10%">
    @foreach(var item in Model)
{
    <div class="col-auto" style="padding:10px; margin:10px">
        <div class="card shadow-lg p-3 mb-5 bg-#444444 rounded " style="width: 20rem;">
            <div class="text-center">
                <img src="/media/products/@item.Image" class="card-img-top" alt="..." style=" width:10rem; height:12rem">
                </div>

  <div class="text-center">
        <h5 class="card-title" style="padding:2px">Bashundhara 
            <p>
                Block: @item.Block Road: @item.Road
            </p>
        </h5>
  </div>

  <div class="text-center">
           <div class="col" style="padding:1px">
          <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn btn-warning" style="width:9rem">Edit</a> 
     </div>
     <div class="col" style="padding:1px">
           <a asp-action="CreateFlat" asp-route-id="@item.Id" class="btn btn-primary" style="width:9rem">Create Flat</a>
     </div>
     <div class="col" style="padding:1px">
         <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn btn-danger" style="width:9rem">Delete</a>
     </div>
      </div>




 

 




</div>





</div> 



   

}
    <hr />
</div>



<div class="d-flex w-100 justify-content-center">
        <pagination page-count="@ViewBag.TotalPages"
                    page-target="/admin/products/@ViewBag.CategorySlug"
                    page-number="@ViewBag.PageNumber"
                    page-range="@ViewBag.PageRange">
        </pagination>
</div>